services:
  - type: web
    name: my-express-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString

databases:
  - name: my-database
    databaseName: my_db
    user: postgres